project_name         = "terraform-chander-demo"
location             = "westeurope"
admin_username       = "chander"
vm_size              = "Standard_F2as_v6"
vm_name              = "chander-vm-demo"
storage_account_name = "stchanderdemo"
datafactory_name     = "chanderdemodatafactory"
