project-name         = "terraform-demo"
location             = "westeurope"
admin-username       = "chander"
vm-size              = "Standard_F2as_v6"
vm-name              = "chander-vm-demo"
storage-account-name = "stchanderdemo"
datafactory-name     = "chanderdemodatafactory"
